
name: Create Release and Build Binaries

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.1, etc.

permissions: 
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            asset_name: av-converter-linux
          - os: macos-latest
            asset_name: av-converter-macos
          - os: windows-latest
            asset_name: av-converter-windows.exe

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --onefile --name "${{ matrix.asset_name }}" converter.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.asset_name }}

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release and Upload Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${{ github.ref_name }}" \
          --generate-notes
        gh release upload "$tag" artifacts/av-converter-linux/av-converter-linux
        gh release upload "$tag" artifacts/av-converter-macos/av-converter-macos
        gh release upload "$tag" artifacts/av-converter-windows.exe/av-converter-windows.exe
